// SPDX-License-Identifier: 0BSD
//
// Generates register wrappers for the GBA
//

type RegField = {
  bits: number;
  offset: number;
  name: string;
};

type Register = {
  reg: string;
  addr: number;
  width: number;
  ops: string;
  fields: RegField[];
};

let tab = 0;
function log(...lines: string[]) {
  const s = '  '.repeat(tab);
  for (const line of lines) {
    console.log('%s%s', s, line);
  }
}

function header() {
  log(
    '// SPDX-License-Identifier: 0BSD',
    '// generated by scripts/gbareg.ts',
    '#pragma once',
    '#include <stdint.h>',
    '',
    'namespace Reg {'
  );
  tab++;
}

function process(reg: string, { addr, width, ops, fields }: Register) {
  const hasRead = ops.includes('r');
  const hasWrite = ops.includes('w');
  const hasUpdate = ops.includes('u');

  const hex = (n: number) => `0x${n.toString(16)}u`;
  const type = `uint${width}_t`;

  if (hasRead) {
    log(`struct ${reg}Reader {`);
    tab++;
    log(`${type} value;`, '');
    for (const { bits, offset, name } of fields) {
      log(
        `uint32_t ${name}() const {`,
        '  uint32_t v = value;',
        `  return (v >> ${offset}) & ${hex(2 ** bits - 1)};`,
        `}`,
      );
    }
    tab--;
    log('};');
  }

  if (hasWrite) {
    log(`struct ${reg}Writer {`);
    tab++;
    log(`${type} value = 0;`, '');
    for (const { bits, offset, name } of fields) {
      if (bits === 1) {
        log(
          `${reg}Writer ${name}(uint32_t v) {`,
          '  if (v) {',
          `    value |= 1u << ${offset};`,
          '  } else {',
          `    value &= ~(1u << ${offset});`,
          '  }',
          '  return *this;',
          '}',
        );
      } else if (bits === width) {
        log(
          `${reg}Writer ${name}(uint32_t v) {`,
          '  value = v;',
          '  return *this;',
          '}',
        );
      } else {
        log(
          `${reg}Writer &${name}(uint32_t v) {`,
          `  value = (value & ~(${hex(2 ** bits - 1)} << ${offset})) | ` +
            `((v & ${hex(2 ** bits - 1)}) << ${offset});`,
          '  return *this;',
          '}',
        );
      }
    }
    log(
      'void done() {',
      `  volatile ${type} *addr = (volatile ${type} *)${hex(addr)};`,
      '  *addr = value;',
      '}',
    );
    tab--;
    log('};');
  }

  if (hasUpdate) {
    log(`struct ${reg}Updater {`);
    tab++;
    log(
      `${type} value = 0;`,
      `${type} mask = 0;`,
      '',
    );
    for (const { bits, offset, name } of fields) {
      if (bits === 1) {
        log(
          `${reg}Updater &${name}(uint32_t v) {`,
          '  if (v) {',
          `    value |= 1u << ${offset};`,
          '  } else {',
          `    value &= ~(1u << ${offset});`,
          '  }',
          `  mask |= 1u << ${offset};`,
          '  return *this;',
          '}',
        );
      } else if (bits === width) {
        log(
          `${reg}Updater &${name}(uint32_t v) {`,
          '  value = v;',
          `  mask = ${hex(2 ** bits - 1)};`,
          '  return *this;',
          '}',
        );
      } else {
        log(
          `${reg}Updater &${name}(uint32_t v) {`,
          `  value = (value & ~(${hex(2 ** bits - 1)} << ${offset})) | ` +
            `((v & ${hex(2 ** bits - 1)}) << ${offset});`,
          `  mask |= ${hex(2 ** bits - 1)} << ${offset};`,
          '  return *this;',
          '}',
        );
      }
    }
    log(
      'void done() {',
      `  volatile ${type} *addr = (volatile ${type} *)${hex(addr)};`,
      '  *addr = (*addr & ~mask) | value;',
      '}',
    );
    tab--;
    log('};');
  }

  log(`namespace ${reg} {`);
  tab++;
  log(
    `static volatile ${type} *addr() {`,
    `  return (volatile ${type} *)${hex(addr)};`,
    '}'
  );
  if (hasRead) {
    log(
      `static ${type} get() {`,
      '  return *addr();',
      '}',
      `static ${reg}Reader read() {`,
      '  return { get() };',
      '}',
    );
  }
  if (hasWrite) {
    log(
      `static void set(${type} v) {`,
      '  *addr() = v;',
      '}',
      `static ${reg}Writer write() {`,
      '  return {};',
      '}'
    );
  }
  if (hasUpdate) {
    log(
      `static ${reg}Updater update() {`,
      '  return {};',
      '}'
    );
  }
  tab--;
  log('}');
}

function footer() {
  tab--;
  log('}');
}

//
// register parser
//

function reg(strings: TemplateStringsArray): Register {
  const source = strings[0];
  const lines = source
    .trim()
    .split('\n')
    .map(line => line.trim())
    .filter(Boolean);
  const [reg, address, ops] = lines[0].split(/\s+/);
  let width = 0;
  const fields = lines.slice(1).map(line => {
    const [bitsStr, nameStr] = line.split(/\s+/);
    const bits = Number(bitsStr);
    const offset = width;
    width += bits;
    const name = nameStr === '_'
      ? `offset${offset}w${bits}`
      : nameStr;
    return { bits, offset, name };
  });
  return { reg, addr: Number.parseInt(address, 16), width, ops, fields };
}

header();
for (const register of [
  reg`DISPCNT 04000000 rwu
    3 mode
    1 cgbMode
    1 frame
    1 hblankFree
    1 objMapping
    1 forcedBlank
    1 bg0
    1 bg1
    1 bg2
    1 bg3
    1 obj
    1 win0
    1 win1
    1 objWin
  `,
  reg`GREEN_SWAP 04000002 rwu
    1 enabled
    15 _
  `,
  reg`DISPSTAT 04000004 rwu
    1 vblankFlag
    1 hblankFlag
    1 vcountFlag
    1 vblank
    1 hblank
    1 vcount
    2 _
    8 vcountFireAt
  `,
  reg`VCOUNT 04000006 r
    8 scanline
    8 _
  `,
  reg`BG0CNT 04000008 rwu
    2 priority
    2 charBase
    2 _
    1 mosaic
    1 color256
    5 screenBase
    1 _
    2 screenSize
  `,
  reg`BG1CNT 0400000a rwu
    2 priority
    2 charBase
    2 _
    1 mosaic
    1 color256
    5 screenBase
    1 _
    2 screenSize
  `,
  reg`BG2CNT 0400000c rwu
    2 priority
    2 charBase
    2 _
    1 mosaic
    1 color256
    5 screenBase
    1 wrap
    2 screenSize
  `,
  reg`BG3CNT 0400000e rwu
    2 priority
    2 charBase
    2 _
    1 mosaic
    1 color256
    5 screenBase
    1 wrap
    2 screenSize
  `,
  reg`BG0HOFS 04000010 w
    9 offset
    7 _
  `,
  reg`BG0VOFS 04000012 w
    9 offset
    7 _
  `,
  reg`BG1HOFS 04000014 w
    9 offset
    7 _
  `,
  reg`BG1VOFS 04000016 w
    9 offset
    7 _
  `,
  reg`BG2HOFS 04000018 w
    9 offset
    7 _
  `,
  reg`BG2VOFS 0400001a w
    9 offset
    7 _
  `,
  reg`BG3HOFS 0400001c w
    9 offset
    7 _
  `,
  reg`BG3VOFS 0400001e w
    9 offset
    7 _
  `,
  reg`BG2PA 04000020 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG2PB 04000022 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG2PC 04000024 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG2PD 04000026 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG2X 04000028 w
    8 fraction
    19 integer
    1 sign
    4 _
  `,
  reg`BG2Y 0400002c w
    8 fraction
    19 integer
    1 sign
    4 _
  `,
  reg`BG3PA 04000030 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG3PB 04000032 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG3PC 04000034 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG3PD 04000036 w
    8 fraction
    7 integer
    1 sign
  `,
  reg`BG3X 04000038 w
    8 fraction
    19 integer
    1 sign
    4 _
  `,
  reg`BG3Y 0400003c w
    8 fraction
    19 integer
    1 sign
    4 _
  `,
  reg`WIN0H 04000040 w
    8 right
    8 left
  `,
  reg`WIN1H 04000042 w
    8 right
    8 left
  `,
  reg`WIN0V 04000044 w
    8 bottom
    8 top
  `,
  reg`WIN1V 04000046 w
    8 bottom
    8 top
  `,
  reg`WININ 04000048 rwu
    4 win0Bg
    1 win0Obj
    1 win0Effect
    2 _
    4 win1Bg
    1 win1Obj
    1 win1Effect
    2 _
  `,
  reg`WINOUT 0400004a rwu
    4 outsideBg
    1 outsideObj
    1 outsideEffect
    2 _
    4 objWinBg
    1 objWinObj
    1 objWinEffect
    2 _
  `,
  reg`MOSAIC 0400004c w
    4 bgH
    4 bgV
    4 objH
    4 objV
  `,
  reg`BLDCNT 04000050 rwu
    1 bg0First
    1 bg1First
    1 bg2First
    1 bg3First
    1 objFirst
    1 backdropFirst
    2 effect
    1 bg0Second
    1 bg1Second
    1 bg2Second
    1 bg3Second
    1 objSecond
    1 backdropSecond
    2 _
  `,
  reg`BLDALPHA 04000052 rwu
    5 eva
    3 _
    5 evb
    3 _
  `,
  reg`BLDY,BLDVAL 04000054 w
    5 evy
    11 _
  `,
  reg`SOUND1CNT_L 04000060 rwu
    3 sweepShift
    1 sweepDirection
    3 sweepTime
    9 _
  `,
  reg`SOUND1CNT_H 04000062 rwu
    6 length
    2 duty
    3 envelopeStep
    1 envelopeDirection
    4 initialVolume
  `,
  reg`SOUND1CNT_X 04000064 rwu
    11 frequency
    3 _
    1 lengthEnable
    1 initial
  `,
  reg`SOUND2CNT_L 04000068 rwu
    6 length
    2 duty
    3 envelopeStep
    1 envelopeDirection
    4 initialVolume
  `,
  reg`SOUND2CNT_H 0400006c rwu
    11 frequency
    3 _
    1 lengthEnable
    1 initial
  `,
  reg`SOUND3CNT_L 04000070 rwu
    5 _
    1 dimension
    1 bank
    1 enable
    8 _
  `,
  reg`SOUND3CNT_H 04000072 rwu
    8 length
    5 _
    2 volume
    1 forceVolume
  `,
  reg`SOUND3CNT_X 04000074 rwu
    11 frequency
    3 _
    1 lengthEnable
    1 initial
  `,
  reg`SOUND4CNT_L 04000078 rwu
    6 length
    2 _
    3 envelopeStep
    1 envelopeDirection
    4 initialVolume
  `,
  reg`SOUND4CNT_H 0400007c rwu
    3 divisor
    1 counterWidth
    4 shiftClock
    6 _
    1 lengthEnable
    1 initial
  `,
  reg`SOUNDCNT_L 04000080 rwu
    3 rightVolume
    1 _
    3 leftVolume
    1 _
    4 rightEnable
    4 leftEnable
  `,
  reg`SOUNDCNT_H 04000082 rwu
    2 psgVolume
    1 dmaAVolume
    1 dmaBVolume
    4 _
    1 dmaARight
    1 dmaALeft
    1 dmaATimer
    1 dmaAReset
    1 dmaBRight
    1 dmaBLeft
    1 dmaBTimer
    1 dmaBReset
  `,
  reg`SOUNDCNT_X 04000084 rwu
    1 sound1
    1 sound2
    1 sound3
    1 sound4
    3 _
    1 master
    8 _
  `,
  reg`SOUNDBIAS 04000088 rwu
    1 _
    9 bias
    4 _
    2 resolution
  `,
  reg`WAVE_RAM0_L 04000090 rw
    16 data
  `,
  reg`WAVE_RAM0_H 04000092 rw
    16 data
  `,
  reg`WAVE_RAM1_L 04000094 rw
    16 data
  `,
  reg`WAVE_RAM1_H 04000096 rw
    16 data
  `,
  reg`WAVE_RAM2_L 04000098 rw
    16 data
  `,
  reg`WAVE_RAM2_H 0400009a rw
    16 data
  `,
  reg`WAVE_RAM3_L 0400009c rw
    16 data
  `,
  reg`WAVE_RAM3_H 0400009e rw
    16 data
  `,
  reg`FIFO_A 040000a0 w
    32 data
  `,
  reg`FIFO_B 040000a4 w
    32 data
  `,
  reg`DMA0SAD,DMA0SRC 040000b0 w
    32 addr
  `,
  reg`DMA0DAD,DMA0DST 040000b4 w
    32 addr
  `,
  reg`DMA0CNT_L,DMA0LEN 040000b8 w
    14 len
    2 _
  `,
  reg`DMA0CNT_H,DMA0CNT 040000ba rwu
    5 _
    2 destControl
    2 sourceControl
    1 repeat
    1 word32
    1 _
    2 timing
    1 irq
    1 enable
  `,
  reg`DMA1SAD,DMA1SRC 040000bc w
    32 addr
  `,
  reg`DMA1DAD,DMA1DST 040000c0 w
    32 addr
  `,
  reg`DMA1CNT_L,DMA1LEN 040000c4 w
    14 len
    2 _
  `,
  reg`DMA1CNT_H,DMA1CNT 040000c6 rwu
    5 _
    2 destControl
    2 sourceControl
    1 repeat
    1 word32
    1 _
    2 timing
    1 irq
    1 enable
  `,
  reg`DMA2SAD,DMA2SRC 040000c8 w
    32 addr
  `,
  reg`DMA2DAD,DMA2DST 040000cc w
    32 addr
  `,
  reg`DMA2CNT_L,DMA2LEN 040000d0 w
    14 len
    2 _
  `,
  reg`DMA2CNT_H,DMA2CNT 040000d2 rwu
    5 _
    2 destControl
    2 sourceControl
    1 repeat
    1 word32
    1 _
    2 timing
    1 irq
    1 enable
  `,
  reg`DMA3SAD,DMA3SRC 040000d4 w
    32 addr
  `,
  reg`DMA3DAD,DMA3DST 040000d8 w
    32 addr
  `,
  reg`DMA3CNT_L,DMA3LEN 040000dc w
    16 len
  `,
  reg`DMA3CNT_H,DMA3CNT 040000de rwu
    5 _
    2 destControl
    2 sourceControl
    1 repeat
    1 word32
    1 gamePakDrq
    2 timing
    1 irq
    1 enable
  `,
  reg`TM0CNT_L,TM0D,TM0VAL 04000100 rw
    16 val
  `,
  reg`TM0CNT_H,TM0CNT 04000102 rwu
    2 prescaler
    1 countUp
    3 _
    1 irq
    1 enable
    8 _
  `,
  reg`TM1CNT_L,TM1D,TM1VAL 04000104 rw
    16 val
  `,
  reg`TM1CNT_H,TM1CNT 04000106 rwu
    2 prescaler
    1 countUp
    3 _
    1 irq
    1 enable
    8 _
  `,
  reg`TM2CNT_L,TM2D,TM2VAL 04000108 rw
    16 val
  `,
  reg`TM2CNT_H,TM2CNT 0400010a rwu
    2 prescaler
    1 countUp
    3 _
    1 irq
    1 enable
    8 _
  `,
  reg`TM3CNT_L,TM3D,TM3VAL 0400010c rw
    16 val
  `,
  reg`TM3CNT_H,TM3CNT 0400010e rwu
    2 prescaler
    1 countUp
    3 _
    1 irq
    1 enable
    8 _
  `,
  reg`SIODATA32 04000120 rwu
    32 data
  `,
  reg`SIOMULTI0 04000120 rwu
    16 data
  `,
  reg`SIOMULTI1 04000122 rwu
    16 data
  `,
  reg`SIOMULTI2 04000124 rwu
    16 data
  `,
  reg`SIOMULTI3 04000126 rwu
    16 data
  `,
  reg`SIOCNT_NORMAL 04000128 rwu
    1 internalClock
    1 fastClock
    1 si
    1 so
    3 _
    1 start
    4 _
    1 word32
    1 _
    1 irq
    1 _
  `,
  reg`SIOCNT_MULTI 04000128 rwu
    2 baud
    1 si
    1 sd
    2 id
    1 error
    1 start
    4 _
    1 _
    1 multiplayer
    1 irq
    1 _
  `,
  reg`SIOCNT_UART 04000128 rwu
    2 baud
    1 cts
    1 oddParity
    1 sendFull
    1 receiveEmpty
    1 error
    1 data8
    1 fifo
    1 parity
    1 send
    1 receive
    2 uart
    1 irq
    1 _
  `,
  reg`SIOMLT_SEND 0400012a rwu
    16 data
  `,
  reg`SIODATA8 0400012a rwu
    8 data
    8 _
  `,
  reg`RCNT 04000134 rwu
    4 pins
    10 _
    1 mode
    1 gpio
  `,
  reg`RCNT_GPIO 04000134 rwu
    1 sc
    1 sd
    1 si
    1 so
    1 scOutput
    1 sdOutput
    1 siOutput
    1 soOutput
    1 siIrq
    5 _
    1 joybus
    1 gpio
  `,
  reg`IR 04000136 rwu
    1 transmit
    1 readEnable
    1 receive
    1 amp
    1 irq
    11 _
  `,
  reg`KEYINPUT 04000130 r
    1 a
    1 b
    1 select
    1 start
    1 right
    1 left
    1 up
    1 down
    1 r
    1 l
    6 _
  `,
  reg`KEYCNT 04000132 rwu
    1 a
    1 b
    1 select
    1 start
    1 right
    1 left
    1 up
    1 down
    1 r
    1 l
    4 _
    1 irq
    1 andMode
  `,
  reg`JOYCNT 04000140 rw
    1 reset
    1 receive
    1 send
    3 _
    1 irq
    9 _
  `,
  reg`JOY_RECV 04000150 rwu
    32 data
  `,
  reg`JOY_TRANS 04000154 rwu
    32 data
  `,
  reg`JOYSTAT 04000158 rwu
    1 _
    1 receive
    1 _
    1 send
    2 flags
    10 _
  `,
  reg`IE 04000200 rwu
    1 vblank
    1 hblank
    1 vcount
    1 timer0
    1 timer1
    1 timer2
    1 timer3
    1 serial
    1 dma0
    1 dma1
    1 dma2
    1 dma3
    1 keypad
    1 gamePak
    2 _
  `,
  reg`IF 04000202 rw
    1 vblank
    1 hblank
    1 vcount
    1 timer0
    1 timer1
    1 timer2
    1 timer3
    1 serial
    1 dma0
    1 dma1
    1 dma2
    1 dma3
    1 keypad
    1 gamePak
    2 _
  `,
  reg`WAITCNT 04000204 rwu
    2 sram
    2 ws0First
    1 ws0Second
    2 ws1First
    1 ws1Second
    2 ws2First
    1 ws2Second
    2 phi
    1 _
    1 prefetch
    1 gamePakType
  `,
  reg`IME 04000208 rwu
    1 enable
    15 _
  `,
  reg`POSTFLG 04000300 rwu
    1 firstBoot
    7 _
  `,
  reg`HALTCNT 04000301 w
    7 _
    1 stop
  `,
  reg`UNDOC_0410 04000410 w
    8 _
  `,
  reg`WRAMCNT 04000800 rwu
    1 disableWram
    3 _
    1 _
    1 enableEwram
    18 _
    4 ewramWait
    4 _
  `,
  reg`MGBA_FLAGS 4fff700 rwu
    3 level
    5 _
    1 log
    7 _
  `,
  reg`MGBA_ENABLE 4fff780 rw
    16 val
  `,
]) {
  for (const reg of register.reg.split(',')) {
    process(reg, register);
  }
}
footer();
