#!/bin/bash
# SPDX-License-Identifier: 0BSD

SCRIPTS="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

find "$SCRIPTS" -type f -name '*.ts' | while read -r file; do
  npx --yes --package=typescript@7.0.2 \
    tsc "$file" \
    --noEmit \
    --strict \
    --target esnext \
    --module preserve \
    --erasableSyntaxOnly
done
